#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.2
#  in conjunction with Tcl version 8.6
#    May 23, 2020 03:37:05 PM PDT  platform: Windows NT

import sys
import mainLogic

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from tkinter import filedialog as fg

def set_Tk_var():
    global ssOrder
    ssOrder = tk.IntVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def loadFolder(Entry1):
    print('slide Main_support.loadFolder')
    pathString = fg.askdirectory()
    print(pathString)
    Entry1.delete("0", tk.END)
    Entry1.insert(tk.END, pathString)
    sys.stdout.flush()

def runShow(Entry1, Entry2):
    print("Entry1:", Entry1.get())
    print("Entry2:", Entry2.get())
    ssTime = Entry2.get()
    ssTime = int(ssTime) if ssTime != '' else 5
    try:
        mainLogic.main(ssOrder.get(), Entry1.get(), ssTime)
    except tk.TclError:
        pass

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import slideMain
    slideMain.vp_start_gui()




